---

  - include_vars: "{{ ansible_os_family }}.yml"

  - name: Ensure SickRage service group exists
    group:
      name: "{{ sickrage_group_name }}"
      gid: "{{ sickrage_group_gid }}"
      system: true
      state: present
           
  - name: Ensure SickRage service user exists
    user:
      name: "{{ sickrage_user_name }}"
      uid: "{{ sickrage_user_uid }}"
      group: "{{ sickrage_group_name }}"
      home: "{{ sickrage_user_home }}"
      system: true
      state: present

  - name: Ensure SickRage dependencies are installed
    package: name={{ sickrage_dependencies }} state=present

  - name: Fetch UnRAR source from RARLAB
    get_url:
      url: http://rarlab.com/rar/unrarsrc-5.2.7.tar.gz
      dest: /root/
      sha256sum: ef14757e943787b439fedf2c564c1f38d0db315528a928e0de170860717e2fac
      
  - name: Ensure UnRAR source has been unarchived
    unarchive:
      src: /root/unrarsrc-5.2.7.tar.gz
      dest: /root/
      copy: false

  - name: Ensure UnRAR has been built
    shell: make -f makefile
    args:
      chdir: /root/unrar
      creates: /root/unrar/unrar

  - name: Ensure UnRAR has been installed
    shell: make -f makefile install
    args:
      chdir: /root/unrar
      creates: /usr/bin/unrar

  - name: Ensure SickRage library directory exists
    file:
      dest: "{{ sickrage_library_path }}"
      owner: "{{ sickrage_user_name }}"
      group: "{{ sickrage_group_name }}"
      state: directory

  - name: Ensure SickRage config directory exists
    file:
      dest: "{{ sickrage_conf_path }}"
      owner: "{{ sickrage_user_name }}"
      group: "{{ sickrage_group_name }}"
      recurse: true
      state: directory

  - name: Fetch SickRage source code
    git:
      repo: "{{ sickrage_clone_uri }}"
      dest: "{{ sickrage_user_home }}/src"
      update: false
      accept_hostkey: true
    become: true
    become_user: "{{ sickrage_user_name }}"

  - name: Deploy SickRage service manifest
    template:
      src: "{{ sickrage_service_file.src }}"
      dest: "{{ sickrage_service_file.dest }}"
      owner: root
      group: root
      mode: 0600
    notify:
      - Reload Sickrage service config
      - Restart Sickrage service

  - meta: flush_handlers

  - name: Ensure SickRage service is running and enabled on boot
    service: name=sickrage state=started enabled=yes
